FROM docker.io/continuumio/miniconda3

# Set working directory
WORKDIR /app

# Copy the Conda environment file
COPY dgl_lib_env_new_ubuntu_environment.yml .

# Create Conda environment
RUN conda env create -n myenv -f dgl_lib_env_new_ubuntu_environment.yml && \
    conda clean --all --yes && \
    rm -rf /opt/conda/pkgs/*

# Copy the wait-for-it.sh script to the /app directory
COPY wait-for-it.sh /app
RUN chmod +x /app/wait-for-it.sh

# Copy the rest of the application code
COPY *.py .

# Command to run your application
CMD /app/wait-for-it.sh db:3306 -- conda run -n myenv python -u hyper_tuning.py